CREATE TABLE table1
(
    column11 integer,
    column12 text
);

CREATE TABLE table2
(
    column21 bigint,
    column22 bigint
);
--
-- CREATE TABLE table3
-- (
--     column31 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     column32 text
-- );
